# Generated by Django 5.0.4 on 2024-07-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='color_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='length',
            field=models.FloatField(blank=True),
        ),
    ]
