# Generated by Django 5.0.4 on 2024-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_artwork_color_type_artworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='artwork_images/'),
        ),
    ]
