# Generated by Django 5.0.4 on 2024-07-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_artwork_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-date_created']},
        ),
    ]
